-- Quality Project Control MAIN V8.0 · Fase 1
-- Permisos granulares, membresías de proyecto y auditoría de administración.
-- Idempotente: puede ejecutarse nuevamente de forma segura.

begin;

-- 1) Perfiles: asegurar columnas y roles vigentes.
alter table public.profiles add column if not exists avatar_data_url text;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

do $$
declare c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'public.profiles'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%role%'
  loop
    execute format('alter table public.profiles drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.profiles
  add constraint profiles_role_check
  check (role in ('EJECUCION','CALIDAD','COORDINADOR_CALIDAD','GERENCIA','PRESIDENTE','IT'));

-- 2) Catálogo de permisos.
create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text not null default '',
  category text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.role_permissions (
  role text not null,
  permission_id bigint not null references public.permissions(id) on delete cascade,
  allowed boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (role, permission_id),
  constraint role_permissions_role_check check (role in ('EJECUCION','CALIDAD','COORDINADOR_CALIDAD','GERENCIA','PRESIDENTE','IT'))
);

create table if not exists public.user_permission_overrides (
  user_id uuid not null references public.profiles(id) on delete cascade,
  permission_id bigint not null references public.permissions(id) on delete cascade,
  allowed boolean not null,
  granted_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, permission_id)
);

-- 3) Asignación relacional de proyectos. project_id es text durante la transición
-- porque la aplicación actual usa códigos como LCE/VC. La migración relacional
-- completa de proyectos se hará en la siguiente fase sin romper datos existentes.
create table if not exists public.project_members (
  project_id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  is_active boolean not null default true,
  assigned_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (project_id, user_id)
);

-- 4) Auditoría mínima para administración.
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  project_id text,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  previous_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

-- 5) Directorio limitado del login.
create table if not exists public.login_directory (
  email text primary key,
  full_name text not null,
  role text not null,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

-- 6) Semilla del catálogo.
insert into public.permissions (code,name,description,category,sort_order) values
('dashboard.view','Ver panel principal','Consultar indicadores del proyecto.','GENERAL',10),
('audit.view','Ver auditoría','Consultar el historial de acciones administrativas.','GENERAL',20),
('settings.manage','Administrar configuración','Modificar configuración global de la plataforma.','GENERAL',30),
('projects.view_assigned','Ver proyectos asignados','Consultar los proyectos asignados al usuario.','PROYECTOS',10),
('projects.view_all','Ver todos los proyectos','Consultar todos los proyectos.','PROYECTOS',20),
('projects.create','Crear proyectos','Crear proyectos nuevos.','PROYECTOS',30),
('projects.edit','Modificar proyectos','Modificar información general de proyectos.','PROYECTOS',40),
('projects.archive','Archivar proyectos','Archivar o restaurar proyectos.','PROYECTOS',50),
('projects.structure.manage','Gestionar estructura','Administrar bloques, niveles y áreas.','PROYECTOS',60),
('projects.assign_users','Asignar usuarios','Asignar usuarios a proyectos.','PROYECTOS',70),
('users.view','Ver usuarios','Consultar usuarios y perfiles.','USUARIOS',10),
('users.create.execution','Crear Ejecución','Crear Ingenieros de Ejecución.','USUARIOS',20),
('users.edit.execution','Editar Ejecución','Modificar Ingenieros de Ejecución.','USUARIOS',30),
('users.create.quality','Crear Calidad','Crear Ingenieros de Calidad.','USUARIOS',40),
('users.edit.quality','Editar Calidad','Modificar Ingenieros de Calidad.','USUARIOS',50),
('users.create.quality_manager','Crear Gerente de Calidad','Crear Gerentes de Calidad.','USUARIOS',60),
('users.edit.quality_manager','Editar Gerente de Calidad','Modificar Gerentes de Calidad.','USUARIOS',70),
('users.create.project_manager','Crear Gerente de Proyecto','Crear Gerentes de Proyecto.','USUARIOS',80),
('users.edit.project_manager','Editar Gerente de Proyecto','Modificar Gerentes de Proyecto.','USUARIOS',90),
('users.create.president','Crear Presidencia','Crear usuarios de Presidencia.','USUARIOS',100),
('users.edit.president','Editar Presidencia','Modificar usuarios de Presidencia.','USUARIOS',110),
('users.create.it','Crear Tecnología IT','Crear usuarios de Tecnología.','USUARIOS',120),
('users.edit.it','Editar Tecnología IT','Modificar usuarios de Tecnología.','USUARIOS',130),
('users.activate_deactivate','Activar o desactivar','Cambiar el estado activo de usuarios.','USUARIOS',140),
('users.assign_projects','Asignar proyectos','Cambiar proyectos permitidos.','USUARIOS',150),
('users.permissions.manage','Gestionar permisos','Conceder o denegar permisos individuales.','USUARIOS',160),
('users.password.reset','Restablecer contraseñas','Cambiar o restaurar contraseñas existentes.','USUARIOS',170),
('inspections.request_release','Solicitar liberación','Crear solicitudes de liberación.','INSPECCIONES',10),
('inspections.view_own','Ver inspecciones propias','Consultar inspecciones creadas por el usuario.','INSPECCIONES',20),
('inspections.view_project','Ver inspecciones del proyecto','Consultar inspecciones del proyecto asignado.','INSPECCIONES',30),
('inspections.view_all','Ver todas las inspecciones','Consultar inspecciones de todos los proyectos.','INSPECCIONES',40),
('inspections.take','Tomar inspecciones','Asignarse solicitudes de inspección.','INSPECCIONES',50),
('inspections.evaluate','Evaluar inspecciones','Completar planillas y calificaciones.','INSPECCIONES',60),
('inspections.start_follow_up','Iniciar seguimiento','Crear visitas de seguimiento.','INSPECCIONES',70),
('inspections.start_closure','Iniciar cierre','Crear visitas de cierre.','INSPECCIONES',80),
('inspections.mark_improper','Marcar improcedente','Marcar solicitudes improcedentes.','INSPECCIONES',90),
('inspections.edit_open_visit','Editar visita abierta','Modificar visitas no finalizadas.','INSPECCIONES',100),
('inspections.edit_closed_visit','Editar visita cerrada','Corregir visitas cerradas con auditoría.','INSPECCIONES',110),
('inspections.void','Anular inspecciones','Anular inspecciones.','INSPECCIONES',120),
('inspections.attachments.view','Ver adjuntos','Visualizar evidencias y documentos.','INSPECCIONES',130),
('inspections.attachments.upload','Subir adjuntos','Cargar evidencias y documentos.','INSPECCIONES',140),
('inspections.attachments.delete','Eliminar adjuntos','Eliminar evidencias y documentos.','INSPECCIONES',150),
('ratings.view','Ver calificaciones','Consultar calificaciones.','CALIFICACIONES',10),
('ratings.view_engineers','Ver comparativo por ingeniero','Consultar comparativos por ingeniero.','CALIFICACIONES',20),
('ratings.view_workshops','Ver resultados por taller','Consultar resultados por taller.','CALIFICACIONES',30),
('ratings.view_weak_points','Ver puntos débiles','Consultar puntos débiles.','CALIFICACIONES',40),
('exports.csv','Exportar CSV','Generar archivos CSV.','EXPORTACIONES',10),
('exports.pdf','Exportar PDF','Generar y previsualizar PDF.','EXPORTACIONES',20),
('exports.equipment','Exportar equipos','Exportar seguimiento de equipos.','EXPORTACIONES',30),
('exports.inspections','Exportar inspecciones','Exportar inspecciones y visitas.','EXPORTACIONES',40),
('exports.workshops','Exportar talleres','Exportar resultados por taller.','EXPORTACIONES',50),
('exports.engineers','Exportar ingenieros','Exportar comparativos por ingeniero.','EXPORTACIONES',60),
('exports.weak_points','Exportar puntos débiles','Exportar puntos débiles.','EXPORTACIONES',70),
('equipment.view','Ver equipos','Consultar verificación de equipos.','EQUIPOS',10),
('equipment.create','Crear equipos','Agregar equipos.','EQUIPOS',20),
('equipment.edit','Editar equipos','Modificar equipos.','EQUIPOS',30),
('equipment.delete','Eliminar equipos','Eliminar o desactivar equipos.','EQUIPOS',40),
('equipment.verify','Verificar equipos','Registrar verificaciones.','EQUIPOS',50),
('equipment.import','Importar equipos','Importar archivos FO-GC-23.','EQUIPOS',60),
('equipment.export','Exportar equipos','Exportar el listado de equipos.','EQUIPOS',70),
('instructives.view','Ver instructivos','Consultar instructivos.','INSTRUCTIVOS',10),
('instructives.create','Crear instructivos','Agregar instructivos.','INSTRUCTIVOS',20),
('instructives.edit','Editar instructivos','Modificar instructivos.','INSTRUCTIVOS',30),
('instructives.delete','Eliminar instructivos','Eliminar o archivar instructivos.','INSTRUCTIVOS',40),
('instructives.version','Versionar instructivos','Crear versiones y obsoletar anteriores.','INSTRUCTIVOS',50),
('mappings.view','Ver mapeos','Consultar mapeos.','MAPEOS',10),
('mappings.create','Crear mapeos','Agregar mapeos.','MAPEOS',20),
('mappings.edit','Editar mapeos','Modificar mapeos.','MAPEOS',30),
('mappings.delete','Eliminar mapeos','Eliminar o archivar mapeos.','MAPEOS',40),
('mappings.annotate','Resaltar mapeos','Crear anotaciones y resaltados.','MAPEOS',50),
('profile.edit_own','Editar perfil propio','Cambiar nombre visible e imagen personal.','PERFIL',10)
on conflict (code) do update set
  name=excluded.name,
  description=excluded.description,
  category=excluded.category,
  sort_order=excluded.sort_order;

-- 7) Función auxiliar para asignar defaults de forma idempotente.
create or replace function public.qpc_set_role_permission(p_role text,p_code text,p_allowed boolean default true)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.role_permissions(role,permission_id,allowed)
  select p_role,id,p_allowed from public.permissions where code=p_code
  on conflict (role,permission_id) do update set allowed=excluded.allowed,updated_at=now();
end;
$$;

-- Limpiar defaults administrados por esta migración para reconstruirlos.
delete from public.role_permissions
where role in ('EJECUCION','CALIDAD','COORDINADOR_CALIDAD','GERENCIA','PRESIDENTE','IT');

-- IT: absolutamente todos los permisos.
insert into public.role_permissions(role,permission_id,allowed)
select 'IT',id,true from public.permissions
on conflict (role,permission_id) do update set allowed=true,updated_at=now();

-- Ejecución.
select public.qpc_set_role_permission('EJECUCION',code,true)
from public.permissions
where code in (
  'dashboard.view','projects.view_assigned','inspections.request_release','inspections.view_own',
  'inspections.attachments.view','inspections.attachments.upload','instructives.view','mappings.view',
  'mappings.annotate','profile.edit_own'
);

-- Calidad.
select public.qpc_set_role_permission('CALIDAD',code,true)
from public.permissions
where code in (
  'dashboard.view','projects.view_assigned','projects.create','projects.edit','projects.structure.manage',
  'users.view','users.create.execution','users.edit.execution','users.activate_deactivate',
  'users.assign_projects','users.permissions.manage','users.password.reset',
  'inspections.view_project','inspections.take','inspections.evaluate','inspections.start_follow_up',
  'inspections.start_closure','inspections.mark_improper','inspections.edit_open_visit',
  'inspections.attachments.view','inspections.attachments.upload','inspections.attachments.delete',
  'ratings.view','ratings.view_engineers','ratings.view_workshops','ratings.view_weak_points',
  'exports.csv','exports.pdf','exports.equipment','exports.inspections','exports.workshops',
  'exports.engineers','exports.weak_points','equipment.view','equipment.create','equipment.edit',
  'equipment.delete','equipment.verify','equipment.import','equipment.export','instructives.view',
  'instructives.create','instructives.edit','instructives.delete','instructives.version',
  'mappings.view','mappings.create','mappings.edit','mappings.delete','mappings.annotate','profile.edit_own'
);

-- Gerente de Calidad: Calidad + gestión de Calidad.
insert into public.role_permissions(role,permission_id,allowed)
select 'COORDINADOR_CALIDAD',permission_id,allowed from public.role_permissions where role='CALIDAD'
on conflict (role,permission_id) do update set allowed=excluded.allowed,updated_at=now();
select public.qpc_set_role_permission('COORDINADOR_CALIDAD',code,true)
from public.permissions
where code in ('users.create.quality','users.edit.quality','audit.view','projects.assign_users');

-- Gerente de Proyecto: consulta, proyectos, exportaciones y administración jerárquica.
select public.qpc_set_role_permission('GERENCIA',code,true)
from public.permissions
where code in (
  'dashboard.view','audit.view','projects.view_all','projects.create','projects.edit','projects.archive',
  'projects.structure.manage','projects.assign_users','users.view','users.create.execution','users.edit.execution',
  'users.create.quality','users.edit.quality','users.create.quality_manager','users.edit.quality_manager',
  'users.create.project_manager','users.edit.project_manager','users.activate_deactivate',
  'users.assign_projects','users.permissions.manage','inspections.view_project','inspections.attachments.view',
  'ratings.view','ratings.view_engineers','ratings.view_workshops','ratings.view_weak_points',
  'exports.csv','exports.pdf','exports.equipment','exports.inspections','exports.workshops',
  'exports.engineers','exports.weak_points','profile.edit_own'
);

-- Presidencia: administración global; instructivos/mapeos no son visibles por defecto.
select public.qpc_set_role_permission('PRESIDENTE',code,true)
from public.permissions
where code not like 'instructives.%'
  and code not like 'mappings.%'
  and code not in ('inspections.request_release','inspections.take','inspections.evaluate',
                   'inspections.start_follow_up','inspections.start_closure','inspections.mark_improper',
                   'inspections.edit_open_visit','equipment.create','equipment.edit','equipment.delete',
                   'equipment.verify','equipment.import');

-- 8) Sincronizar membresías existentes desde project_ids.
insert into public.project_members(project_id,user_id,is_active,assigned_by)
select project_id,p.id,p.is_active,null
from public.profiles p
cross join lateral unnest(coalesce(p.project_ids,array[]::text[])) as project_id
where project_id is not null and project_id<>''
on conflict (project_id,user_id) do update set is_active=excluded.is_active,updated_at=now();

-- 9) Funciones de autorización. service_role y SECURITY DEFINER son usados por
-- Edge Functions; el frontend nunca recibe la service_role.
create or replace function public.user_has_permission_for(p_user_id uuid,p_permission_code text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select case
    when exists(select 1 from public.profiles p where p.id=p_user_id and p.is_active and p.role='IT') then true
    when exists(
      select 1
      from public.user_permission_overrides uo
      join public.permissions pe on pe.id=uo.permission_id
      where uo.user_id=p_user_id and pe.code=p_permission_code
    ) then coalesce((
      select uo.allowed
      from public.user_permission_overrides uo
      join public.permissions pe on pe.id=uo.permission_id
      where uo.user_id=p_user_id and pe.code=p_permission_code
      limit 1
    ),false)
    else coalesce((
      select rp.allowed
      from public.profiles p
      join public.role_permissions rp on rp.role=p.role
      join public.permissions pe on pe.id=rp.permission_id
      where p.id=p_user_id and p.is_active and pe.code=p_permission_code
      limit 1
    ),false)
  end;
$$;

create or replace function public.current_user_has_permission(p_permission_code text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.user_has_permission_for(auth.uid(),p_permission_code);
$$;

revoke all on function public.user_has_permission_for(uuid,text) from public;
grant execute on function public.user_has_permission_for(uuid,text) to authenticated,service_role;
revoke all on function public.current_user_has_permission(text) from public;
grant execute on function public.current_user_has_permission(text) to authenticated;

-- 10) RLS de catálogos y asignaciones.
alter table public.permissions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.user_permission_overrides enable row level security;
alter table public.project_members enable row level security;
alter table public.audit_logs enable row level security;
alter table public.login_directory enable row level security;

drop policy if exists permissions_read_authenticated on public.permissions;
create policy permissions_read_authenticated on public.permissions for select to authenticated using (true);

drop policy if exists role_permissions_read_authenticated on public.role_permissions;
create policy role_permissions_read_authenticated on public.role_permissions for select to authenticated using (true);

drop policy if exists overrides_read_authorized on public.user_permission_overrides;
create policy overrides_read_authorized on public.user_permission_overrides for select to authenticated
using (user_id=auth.uid() or public.current_user_has_permission('users.permissions.manage'));

drop policy if exists project_members_read_authorized on public.project_members;
create policy project_members_read_authorized on public.project_members for select to authenticated
using (user_id=auth.uid() or public.current_user_has_permission('users.view'));

drop policy if exists audit_read_authorized on public.audit_logs;
create policy audit_read_authorized on public.audit_logs for select to authenticated
using (public.current_user_has_permission('audit.view'));

drop policy if exists anon_read_login_directory on public.login_directory;
create policy anon_read_login_directory on public.login_directory for select to anon,authenticated using (is_active=true);

grant select on public.permissions,public.role_permissions,public.user_permission_overrides,public.project_members to authenticated;
grant select on public.audit_logs to authenticated;
grant select on public.login_directory to anon,authenticated;

-- 11) Índices.
create index if not exists idx_role_permissions_role on public.role_permissions(role);
create index if not exists idx_user_permission_overrides_user on public.user_permission_overrides(user_id);
create index if not exists idx_project_members_user on public.project_members(user_id,is_active);
create index if not exists idx_project_members_project on public.project_members(project_id,is_active);
create index if not exists idx_audit_logs_actor_created on public.audit_logs(actor_id,created_at desc);
create index if not exists idx_audit_logs_entity on public.audit_logs(entity_type,entity_id,created_at desc);

-- 12) Actualizar directorio.
insert into public.login_directory(email,full_name,role,is_active,updated_at)
select lower(email),full_name,role,is_active,now() from public.profiles where email is not null
on conflict(email) do update set
  full_name=excluded.full_name,
  role=excluded.role,
  is_active=excluded.is_active,
  updated_at=now();

commit;

-- Verificación resumida.
select category,count(*) as permisos from public.permissions group by category order by category;
select role,count(*) filter(where allowed) as permisos_activos from public.role_permissions group by role order by role;
